version: "3.8"
services:
  client:
    build: ./client
    container_name: client_container
    image: client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - ./app/node_modules
  server:
    build: ./server
    container_name: server_container
    image: server
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
      - ./app/node_modules